### ISSUE TITLE
Improve react-redux layouts

### ISSUE THREAD

**Issue by samdj** [nfour/js-structures#7]
https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/containers

Utlize this structure, of folders for each component/container in order to encapsulate css, images, tests etc..

Additionally, utilize this practice to keep actions and reducers connected:
https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/redux

Also, constants are present throughout the top react-redux boilerplates. We should use them for reducers/actions.
- [x] Encapsulation folders
- [x] Aggregate reducers & actions together
- [x] Use globals constants

**Comment by samdj** [comment]
@peon374 thoughts?

**Comment by nfour** [comment]
Layout is in place at:

https://github.com/nfour/js-structures/tree/master/layouts/react-redux-modular-airbnb/client

Wondering if `redux` is a good name for the logic folder.

Naming it instead `store` is clear, and encapsulating actions & reducers within that is also reasonable as in a react-redux app, actions typically act as async store mutators. Additionally, `sources` would exist within `store`.

At this point you're left with a simplification of code modularization.
- `components` house reusable parts, including their dependencies
- `containers` facilitate mapping the `store` to a view
- `store` keeps state

That would be easy to document.

**Comment by samdj** [comment]
Confirmed good

**Comment by samdj** [comment]
Confirmed good

**Comment by samdj** [comment]
Confirmed good

**Comment by samdj** [comment]
Confirmed good

**Comment by samdj** [comment]
Confirmed good

**Comment by samdj** [comment]
Confirmed good
